services:
    accounts:
      image: "xwei666/accounts:s4"
      container_name: "accounts-ms"
      ports:
          - "8080:8080"
      deploy:
        resources:
          limits:
            memory: "700m"
#        restart: always
      networks:
        - eazybank
    loans :
      image: "xwei666/loans:s4"
      container_name: "loans-ms"
      ports:
        - "8090:8090"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - eazybank
#      restart: always
    cards :
      image: "xwei666/cards:s4"
      container_name: "cards-ms"
      ports:
        - "9000:9000"
      deploy:
        resources:
          limits:
            memory: "700m"
      networks:
        - eazybank
networks:
  eazybank:
    driver: "bridge"